codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range: 70..100
  round: down
  status:
    changes: false
    patch:
      default:
        target: auto
        threshold: 20%
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    project:
      default:
        target: auto
        threshold: 20%
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
