image: registry.gitlab.com/radekkozak/android-docker:latest

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - reports
  - pages

build:
  stage: build
  script:
    - ./gradlew :rxnetwork:clean :rxnetwork:assembleDebug
  artifacts:
      paths:
      - rxnetwork/build/outputs/aar/

unitTests:
  stage: test
  script:
    - ./gradlew :rxnetwork:jacocoTestDebugUnitTestReport
  artifacts:
      paths:
      - rxnetwork/build/reports/tests/
      - rxnetwork/build/reports/jacoco/

codeCoverage:
  stage: reports
  script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN

trigger_docs:
  stage: pages
  script:
    - "HTTP_STATUS=$(curl -X POST -F token=${DOCS_TRIGGER_TOKEN} -F ref=gh-pages -F variables[PROJECT]=${CI_PROJECT_NAME} --silent --output curl.log --write-out '%{http_code}' https://gitlab.com/api/v4/projects/2951036/trigger/pipeline)"
    - if [ "${HTTP_STATUS}" -ne "201" ]; then echo "Error ${HTTP_STATUS}"; cat curl.log; echo; exit 1; fi
  only:
    - master
