language: android
jdk: oraclejdk8
sudo: required # false for Container-Based Infrastructure, required for Sudo-enabled Infrastructure

env:
  global:
    - API=25
    - BUILD_TOOLS=25.0.3

android:
  components:
    - platform-tools
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-$BUILD_TOOLS
    - android-$API
    - extra-android-support
    - extra-android-m2repository

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.m2

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  - chmod ugo+x gradlew
  - chmod ugo+x .scripts/deploy-website.sh

script:
  - ./gradlew rxnetwork:clean rxnetwork:assembleDebug rxnetwork:testDebugUnitTest rxnetwork:jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  - ./.scripts/deploy-website.sh
